#use_frameworks!
install! 'cocoapods', :deterministic_uuids => false
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

# 定义阿里云播放器 SDK 及相关组件
def alivc_sdk_pods
  # 播放器 SDK 版本（建议保持与官方最新版本一致）
  # 参考更新日志：https://help.aliyun.com/zh/vod/developer-reference/release-notes-for-apsaravideo-player-sdk-for-ios
  player_sdk_version = '7.10.0'
  
  # Rts低延时直播组件版本（建议保持与官方最新版本一致）
  # 您可以参考官网获取 RTS SDK 最新版本：https://help.aliyun.com/zh/live/pull-streams-over-rts-on-ios
  rts_sdk_version = '7.10.0'
  
  # 播放器SDK
  pod 'AliPlayerSDK_iOS', player_sdk_version
  # 播放器与Rts低延时直播组件的桥接层（AlivcArtc），版本号需要与播放器一致，需要和 Rts低延时直播组件 一起集成
  pod 'AliPlayerSDK_iOS_ARTC', player_sdk_version
  # Rts低延时直播组件
  pod 'RtsSDK', rts_sdk_version
  
  # API 示例模块，依赖本地路径下的 podspec 文件
  pod "API-Example/AliPlayerSDK_iOS", :path => "../"
  
  # 如需集成其他 SDK（如 AliVCSDK_Standard），取消注释并按需添加
  # pod "API-Example/AliVCSDK_Standard", :path => "../"
end

# 第三方依赖库配置
def third_party_pods
  # 可自定义第三方库版本
end

# 主应用 Target
target 'Example' do
  
  third_party_pods
  
  alivc_sdk_pods
  
  # Common 基础模块
  pod "Common", :path => "../Common"
  
  # 主 App 模块
  pod "App", :path => "../App"
  
  # BasicPlayback 模块
  pod "BasicPlayback", :path => "../BasicPlayback"
  
  # BasicLiveStream 模块
  pod "BasicLiveStream", :path => "../BasicLiveStream"

  # RtsLiveStream 模块
  pod "RtsLiveStream", :path => "../RtsLiveStream"
  
  # Thumbnail 模块
  pod "Thumbnail", :path => "../Thumbnail"
  
  # ExternalSubtitle 模块
  pod "ExternalSubtitle", :path => "../ExternalSubtitle"

  # VttSubtitle 模块
  pod "ExternalSubtitleVtt", :path => "../ExternalSubtitleVtt"
  
  # Preload 模块
  pod "Preload", :path => "../Preload"
  
  # Picture in Picture
  pod "PictureInPicture", :path => "../PictureInPicture"
  
  # AVSampleBufferDisplayLayer 与全局帧投递的画中画方案模块
  pod "PipDisplayLayer", :path => "../PipDisplayLayer"
  
  # 悬浮窗
  pod "FloatWindow", :path => "../FloatWindow"
  
  # multi-resolution
  pod "MultiResolution", :path => "../MultiResolution"
  
  # 安全下载模块
  pod "Downloader", :path => "../Downloader"
end

# 安装后配置
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
end
